---
sidebar: sidebar
permalink: task-blob-enable-data-services.html
keywords: blob storage, blob working environment, azure blob storage accounts, azure blob working environment
summary: After you discover Azure Blob storage accounts in BlueXP, you can use NetApp data services for backup, tiering, and data synchronization.
---

= Use NetApp data services with Azure Blob storage
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
After you discover Azure Blob storage accounts in BlueXP, you can use NetApp data services for backup, tiering, and data synchronization.

* Use *BlueXP backup and recovery* to back up data from your on-premises ONTAP and Cloud Volumes ONTAP systems to Azure Blob storage.
+
To get started, go to the Canvas and drag and drop an on-premises ONTAP or Cloud Volumes ONTAP working environment on your Azure Blob Storage working environment.
+
https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html[Learn more about backing up ONTAP data to Azure Blob storage^].

* Use *BlueXP tiering* to tier inactive data from on-premises ONTAP clusters to Azure Blob storage.
+
To get started, go to the Canvas and drag and drop an on-premises ONTAP working environment on your Azure Blob Storage working environment.
+
https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-azure.html[Learn more about tiering ONTAP data to Azure Blob storage^].

* Use *BlueXP copy and sync* to synchronize data to or from Azure Blob storage accounts.
+
To get started, go to the Canvas and drag and drop the source working environment on the target working environment. Your Azure Blob Storage working environment can be either the source or target. 
+
You can also select your Azure Blob Storage working environment and click *Copy & sync* from the Services panel to synchronize data to or from Azure Blob storage accounts.
+
https://docs.netapp.com/us-en/bluexp-copy-sync/concept-cloud-sync.html[Learn more about the BlueXP copy and sync service^].
